apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5jb2RlLmZiaS5oLWRhLmRlIjoge30KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wLmV4ZSIKfQ==
type: kubernetes.io/dockerconfigjson

