warehouse:
  listenIP: "0.0.0.0"
  udpPort: 4444
  tcpPort: 8000
  logFileDir: "/var/supplywatch/log/"


sensorWarehouse:
  delay: 500 # time between packets in milliseconds
  numOfPackets: 5 # 0 means infinite
  #udpPort: 4444 # should match warehouse udpPort
