warehouse:
  listenIP: "0.0.0.0"
  udpPort: 4444
  tcpPort: 8000

sensorWarehouse:
  udpPort: 4444 # should match warehouse udpPort
  delay: 2 # time between packets
  numOfPackets: 10 # 0 means infinite
