version: '3'
services:
  warehouse_1:
    container_name: warehouse_1
    hostname: warehouse_1
    build:
      context: .
      dockerfile: ./build/warehouse/Dockerfile
      args:
        project: ./cmd/warehouse/
    ports:
      - "4444:4444/udp"
      - "8000:8000/tcp"
    environment:
      SW_UDPPORT: 4444
      SW_TCPPORT: 8000
      SW_LISTEN_IP: "0.0.0.0"
    networks:
      - monorepo_net
    volumes:
      - /var/supplywatch/log:/var/supplywatch/log
  warehouse_2:
    container_name: warehouse_2
    hostname: warehouse_2
    build:
      context: .
      dockerfile: ./build/warehouse/Dockerfile
      args:
        project: ./cmd/warehouse/
    ports:
      - "4445:4445/udp"
      - "8001:8001/tcp"
    environment:
      SW_UDPPORT: 4445
      SW_TCPPORT: 8001
      SW_LISTEN_IP: "0.0.0.0"
    networks:
      - monorepo_net
    volumes:
      - /var/supplywatch/log:/var/supplywatch/log
    depends_on:
      - warehouse_1
  sensor_1:
    container_name: sensor_1
    hostname: sensor_1
    depends_on:
      - warehouse_2
    build:
      context: .
      dockerfile: ./build/sensor/Dockerfile
      args:
        project: ./cmd/sensor/
    environment:
      - APP_NAME=sensor
    networks:
      - monorepo_net
  sensor_2:
    container_name: sensor_2
    hostname: sensor_2
    depends_on:
      - warehouse_2
    build:
      context: .
      dockerfile: ./build/sensor/Dockerfile
      args:
        project: ./cmd/sensor/
    environment:
      - APP_NAME=sensor
    networks:
      - monorepo_net
  sensor_3:
    container_name: sensor_3
    hostname: sensor_3
    depends_on:
      - warehouse_2
    build:
      context: .
      dockerfile: ./build/sensor/Dockerfile
      args:
        project: ./cmd/sensor/
    environment:
      - APP_NAME=sensor
    networks:
      - monorepo_net

networks:
  monorepo_net:
    driver: bridge
