version: '3'
services:
  warehouse:
    container_name: warehouse
    hostname: warehouse
    build:
      context: .
      dockerfile: ./Docker/warehouse/Dockerfile
      args:
        project: ./cmd/warehouse/
    environment:
      - PORT=4444
      - APP_NAME=warehouse
    ports:
      - "4444:4444/udp"
      - "8000:8000/tcp"
    volumes:
      - warehouse_vol:/usr/src/echo/
    networks:
      - monorepo_net
  sensor-warehouse:
    container_name: sensor-warehouse
    hostname: sensor-warehouse
    depends_on:
      - warehouse
    build:
      context: .
      dockerfile: ./Docker/sensor-warehouse/Dockerfile
      args:
        project: ./cmd/sensor-warehouse/
    environment:
      - APP_NAME=sensor-warehouse
    volumes:
      - sensor-warehouse_vol:/usr/src/calypso/
    networks:
      - monorepo_net

volumes:
  sensor-warehouse_vol:
  warehouse_vol:

networks:
  monorepo_net:
    driver: bridge
