version: '3'
services:
  warehouse:
    container_name: warehouse
    hostname: warehouse
    build:
      context: .
      dockerfile: ./Docker/warehouse/Dockerfile
      args:
        project: ./cmd/warehouse/
    ports:
      - "4444:4444/udp"
      - "8000:8000/tcp"
    environment:
      - APP_NAME=warehouse
    networks:
      - monorepo_net
  sensor-warehouse_1:
    container_name: sensor-warehouse_1
    hostname: sensor-warehouse_1
    depends_on:
      - warehouse
    build:
      context: .
      dockerfile: ./Docker/sensor-warehouse/Dockerfile
      args:
        project: ./cmd/sensor-warehouse/
    environment:
      - APP_NAME=sensor-warehouse
    networks:
      - monorepo_net
  sensor-warehouse_2:
    container_name: sensor-warehouse_2
    hostname: sensor-warehouse_2
    depends_on:
      - warehouse
    build:
      context: .
      dockerfile: ./Docker/sensor-warehouse/Dockerfile
      args:
        project: ./cmd/sensor-warehouse/
    environment:
      - APP_NAME=sensor-warehouse
    networks:
      - monorepo_net

networks:
  monorepo_net:
    driver: bridge
