version: '3'
services:
  warehouse_database_1:
    container_name: warehouse_database_1
    image: postgres:12.3-alpine
    env_file:
      - configurations/postgresql.env
    command:
      - -c
      - max_connections=1024
    networks:
      - warehouse_net
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "61833:5432/tcp"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supplywatch"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  warehouse_database_2:
    container_name: warehouse_database_2
    image: postgres:12.3-alpine
    env_file:
      - configurations/postgresql.env
    command:
      - -c
      - max_connections=1024
    networks:
      - warehouse_net
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    depends_on:
      warehouse_database_1:
        condition: service_healthy
    ports:
      - "61832:5432/tcp"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supplywatch"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  warehouse_1:
    container_name: warehouse_1
    hostname: warehouse_1
    build:
      context: .
      dockerfile: ./build/warehouse/Dockerfile
      args:
        project: ./cmd/warehouse/
    ports:
      - "4444:4444/udp"
      - "8000:8000/tcp"
      - "6666:6666/tcp"
    environment:
      SW_UDPPORT: 4444
      SW_TCPPORT: 8000
      SW_GRPCPORT: 6666
      SW_LISTEN_IP: "0.0.0.0"
      SW_OTHER_WAREHOUSE_HOST: warehouse_2
      SW_OTHER_WAREHOUSE_PORT: 6667
      SW_DATABASE: warehouse_database_1
    networks:
      - warehouse_net
    volumes:
      - /var/supplywatch/log:/var/supplywatch/log
    depends_on:
      warehouse_database_2:
        condition: service_healthy
  warehouse_2:
    container_name: warehouse_2
    hostname: warehouse_2
    build:
      context: .
      dockerfile: ./build/warehouse/Dockerfile
      args:
        project: ./cmd/warehouse/
    ports:
      - "4445:4445/udp"
      - "8001:8001/tcp"
      - "6667:6667/tcp"
    environment:
      SW_UDPPORT: 4445
      SW_TCPPORT: 8001
      SW_GRPCPORT: 6667
      SW_LISTEN_IP: "0.0.0.0"
      SW_OTHER_WAREHOUSE_HOST: warehouse_1
      SW_OTHER_WAREHOUSE_PORT: 6666
      SW_DATABASE: warehouse_database_2
    networks:
      - warehouse_net
    volumes:
      - /var/supplywatch/log:/var/supplywatch/log
    depends_on:
      - warehouse_1
  sensor_1:
    container_name: sensor_1
    hostname: sensor_1
    depends_on:
      - warehouse_2
    build:
      context: .
      dockerfile: ./build/sensor/Dockerfile
      args:
        project: ./cmd/sensor/
    environment:
      - APP_NAME=sensor
    networks:
      - warehouse_net
  sensor_2:
    container_name: sensor_2
    hostname: sensor_2
    depends_on:
      - warehouse_2
    build:
      context: .
      dockerfile: ./build/sensor/Dockerfile
      args:
        project: ./cmd/sensor/
    environment:
      - APP_NAME=sensor
    networks:
      - warehouse_net
  sensor_3:
    container_name: sensor_3
    hostname: sensor_3
    depends_on:
      - warehouse_2
    build:
      context: .
      dockerfile: ./build/sensor/Dockerfile
      args:
        project: ./cmd/sensor/
    environment:
      - APP_NAME=sensor
    networks:
      - warehouse_net

networks:
  warehouse_net:
    driver: bridge

volumes:
  postgres_data:
