version: '3'
services:
  sensor-warehouse:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/sensor-warehouse/
    environment:
      - PORT=3001
      - APP_NAME=sensor-warehouse
    ports:
      - 8001:3001
    restart: on-failure
    volumes:
      - sensor-warehouse_vol:/usr/src/calypso/
    networks:
      - monorepo_net
  warehouse:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/warehouse/
    environment:
      - PORT=3001
      - APP_NAME=warehouse
    ports:
      - 8002:3001
    restart: on-failure
    volumes:
      - warehouse_vol:/usr/src/echo/
    networks:
      - monorepo_net

volumes:
  sensor-warehouse_vol:
  warehouse_vol:

networks:
  monorepo_net:
    driver: bridge
