version: '3'
services:
  warehouse:
    container_name: warehouse
    hostname: warehouse
    build:
      context: .
      dockerfile: ./build/warehouse/Dockerfile
      args:
        project: ./cmd/warehouse/
    ports:
      - "4444:4444/udp"
      - "8000:8000/tcp"
    environment:
      - APP_NAME=warehouse
    networks:
      - monorepo_net
  sensor_1:
    container_name: sensor_1
    hostname: sensor_1
    depends_on:
      - warehouse
    build:
      context: .
      dockerfile: ./build/sensor/Dockerfile
      args:
        project: ./cmd/sensor/
    environment:
      - APP_NAME=sensor
    networks:
      - monorepo_net
  sensor_2:
    container_name: sensor_2
    hostname: sensor_2
    depends_on:
      - warehouse
    build:
      context: .
      dockerfile: ./build/sensor/Dockerfile
      args:
        project: ./cmd/sensor/
    environment:
      - APP_NAME=sensor
    networks:
      - monorepo_net
  sensor_3:
    container_name: sensor_3
    hostname: sensor_3
    depends_on:
      - warehouse
    build:
      context: .
      dockerfile: ./build/sensor/Dockerfile
      args:
        project: ./cmd/sensor/
    environment:
      - APP_NAME=sensor
    networks:
      - monorepo_net

networks:
  monorepo_net:
    driver: bridge
