// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetAllProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllProductsResponse) Reset()         { *m = GetAllProductsResponse{} }
func (m *GetAllProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllProductsResponse) ProtoMessage()    {}
func (*GetAllProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}

func (m *GetAllProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductsResponse.Unmarshal(m, b)
}
func (m *GetAllProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductsResponse.Merge(m, src)
}
func (m *GetAllProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllProductsResponse.Size(m)
}
func (m *GetAllProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductsResponse proto.InternalMessageInfo

func (m *GetAllProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type GetAllProductsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProductsRequest) Reset()         { *m = GetAllProductsRequest{} }
func (m *GetAllProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllProductsRequest) ProtoMessage()    {}
func (*GetAllProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}

func (m *GetAllProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductsRequest.Unmarshal(m, b)
}
func (m *GetAllProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductsRequest.Merge(m, src)
}
func (m *GetAllProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllProductsRequest.Size(m)
}
func (m *GetAllProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductsRequest proto.InternalMessageInfo

type ReceivProductsRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceivProductsRequest) Reset()         { *m = ReceivProductsRequest{} }
func (m *ReceivProductsRequest) String() string { return proto.CompactTextString(m) }
func (*ReceivProductsRequest) ProtoMessage()    {}
func (*ReceivProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{3}
}

func (m *ReceivProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceivProductsRequest.Unmarshal(m, b)
}
func (m *ReceivProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceivProductsRequest.Marshal(b, m, deterministic)
}
func (m *ReceivProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceivProductsRequest.Merge(m, src)
}
func (m *ReceivProductsRequest) XXX_Size() int {
	return xxx_messageInfo_ReceivProductsRequest.Size(m)
}
func (m *ReceivProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceivProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceivProductsRequest proto.InternalMessageInfo

func (m *ReceivProductsRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ReceivProductsRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReceivProductsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceivProductsResponse) Reset()         { *m = ReceivProductsResponse{} }
func (m *ReceivProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ReceivProductsResponse) ProtoMessage()    {}
func (*ReceivProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{4}
}

func (m *ReceivProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceivProductsResponse.Unmarshal(m, b)
}
func (m *ReceivProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceivProductsResponse.Marshal(b, m, deterministic)
}
func (m *ReceivProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceivProductsResponse.Merge(m, src)
}
func (m *ReceivProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ReceivProductsResponse.Size(m)
}
func (m *ReceivProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceivProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceivProductsResponse proto.InternalMessageInfo

func (m *ReceivProductsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Product)(nil), "pb.Product")
	proto.RegisterType((*GetAllProductsResponse)(nil), "pb.GetAllProductsResponse")
	proto.RegisterType((*GetAllProductsRequest)(nil), "pb.GetAllProductsRequest")
	proto.RegisterType((*ReceivProductsRequest)(nil), "pb.ReceivProductsRequest")
	proto.RegisterType((*ReceivProductsResponse)(nil), "pb.ReceivProductsResponse")
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_8c6e54f42122eb82) }

var fileDescriptor_8c6e54f42122eb82 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd7, 0xaa, 0xeb, 0x7c, 0x83, 0x1e, 0x02, 0xab, 0x75, 0xa7, 0x11, 0x90, 0xcd, 0x83,
	0x1d, 0xd4, 0xa3, 0xa7, 0x79, 0x11, 0x6f, 0x12, 0xc1, 0x83, 0xb7, 0x36, 0x0d, 0x2e, 0xd8, 0x34,
	0xb1, 0x49, 0x26, 0x7e, 0x21, 0x3f, 0xa7, 0x2c, 0x4d, 0x85, 0x95, 0xde, 0xfa, 0xde, 0xff, 0xbd,
	0x5f, 0x7f, 0x8f, 0x40, 0xac, 0x5a, 0x59, 0x59, 0x6a, 0x74, 0xa6, 0x5a, 0x69, 0x24, 0x0a, 0x55,
	0x89, 0xef, 0x20, 0x7a, 0xe9, 0xba, 0x28, 0x86, 0x90, 0x57, 0x69, 0xb0, 0x0a, 0x36, 0x97, 0x24,
	0xe4, 0x15, 0x42, 0x70, 0xde, 0x14, 0x82, 0xa5, 0xa1, 0xeb, 0xb8, 0x6f, 0xbc, 0x83, 0xe4, 0x89,
	0x99, 0x5d, 0x5d, 0xfb, 0x25, 0x4d, 0x98, 0x56, 0xb2, 0xd1, 0x0c, 0xad, 0x61, 0xd6, 0xe3, 0xd3,
	0x60, 0x75, 0xb6, 0x99, 0xe7, 0xf3, 0x4c, 0x95, 0x99, 0x9f, 0x23, 0xff, 0x21, 0xbe, 0x82, 0xc5,
	0x10, 0xf1, 0x65, 0x99, 0x36, 0xf8, 0x0d, 0x16, 0x84, 0x51, 0xc6, 0x0f, 0x83, 0x00, 0xdd, 0x40,
	0xe4, 0xb7, 0x9d, 0xdd, 0x80, 0xdc, 0x67, 0x28, 0x81, 0x69, 0x21, 0xa4, 0x6d, 0x8c, 0x33, 0xbe,
	0x20, 0xbe, 0xc2, 0x39, 0x24, 0x43, 0xae, 0x77, 0x4e, 0x21, 0xd2, 0x96, 0x52, 0xa6, 0xb5, 0x03,
	0xcf, 0x48, 0x5f, 0xe6, 0xbf, 0x01, 0xc4, 0x7e, 0xfc, 0x95, 0xb5, 0x07, 0x4e, 0x19, 0x7a, 0x86,
	0xf8, 0xd4, 0x1b, 0x5d, 0x1f, 0x35, 0x46, 0x6f, 0x59, 0x2e, 0xc7, 0xa2, 0xee, 0xaf, 0x78, 0x72,
	0x44, 0x9d, 0x1a, 0x75, 0xa8, 0xd1, 0xeb, 0x3b, 0xd4, 0xf8, 0x01, 0x78, 0xf2, 0x78, 0xfb, 0xbe,
	0xfe, 0xe0, 0x66, 0x6f, 0xcb, 0x8c, 0x4a, 0xb1, 0x15, 0x45, 0xcb, 0xad, 0xfe, 0xe4, 0x42, 0xf0,
	0xa6, 0xd8, 0x6a, 0xab, 0x54, 0xfd, 0xf3, 0x5d, 0x18, 0xba, 0x7f, 0x50, 0x65, 0x39, 0x75, 0xaf,
	0x7e, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x83, 0x47, 0xef, 0xe4, 0x07, 0x02, 0x00, 0x00,
}
