apiVersion: apps/v1
kind: Deployment
metadata:
  name: database1
  labels:
    app: database1
spec:
  selector:
    matchLabels:
      app: database1
  template:
    metadata:
      labels:
        app: database1
    spec:
      containers:
        - name: database1
          image: postgres:10.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: supplywatch
            - name: POSTGRES_USER
              value: supplywatch
            - name: POSTGRES_PASSWORD
              value: test
          volumeMounts:
            - mountPath: /var/lib/postgresql/database1-data
              name: database1-pgdata
      volumes:
        - hostPath:
            path: /home/docker/database1-pgdata
          name: database1-pgdata

