apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  labels:
    app: sensor
spec:
  selector:
    matchLabels:
      app: sensor
  template:
    metadata:
      labels:
        app: sensor
    spec:
      containers:
        - name: sensor
          image: registry.code.fbi.h-da.de/distributed-systems/2020_vsprakt_moore/vs_ws21-22_mi5x-gimbel/mi5x-vfbi-003-team-g/sensor
      imagePullSecrets:
        - name: myregkeytwo
