apiVersion: v1
kind: Service
metadata:
  name: warehouse1
spec:
  selector:
    app: warehouse1
  ports:
  - protocol: TCP
    name: warehouse1-http
    port: 8000
    targetPort: 8000
  - protocol: TCP
    name: warehouse1-grpc
    port: 6666
    targetPort: 6666
